apiVersion: v1
kind: Service
metadata:
   name: mogodbservice
   labels:
      type: service
      app: mogodbservice
spec:
   selector:
      app: db
   ports:
      - protocol: TCP
        port: 27017
        targetPort: 27017
