apiVersion: apps/v1
kind: Deployment
metadata:
   name: express-application
   labels:
      app: application
spec:
   replicas: 1
   selector:
      matchLabels:
        app: application
   template:
      metadata:
        name: application01
        labels:
         app: application
      spec:
         containers: 
            - name: app01
              image: mongo-express
              ports:
                 - containerPort: 8081
              env:
                 - name: ME_CONFIG_MONGODB_SERVER
                   value: mogodbservice
                 - name: ME_CONFIG_MONGODB_ADMINUSERNAME  
                   value: username

                 - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
                   value: password
           
      
