apiVersion: v1
kind: Service
metadata:
   name: application-service
   labels:
     app: express-service
spec:
   selector:
      app: application
   type: LoadBalancer
   externalIPs:
     - 18.208.157.52
   ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
        nodePort: 30000
