apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongodb
   labels:
      app: mongodb
spec:
   replicas: 1
   selector:
      matchLabels:
        app: db
   template:
      metadata:
         name: mongodbpod
         labels:
            app: db
      spec:
         containers:
            - name: mongodb
              image: mongo
              ports:
                 - containerPort: 27017

              env:
                 - name: MONGO_INITDB_ROOT_USERNAME
                   value: username
                 - name: MONGO_INITDB_ROOT_PASSWORD
                   value: password
